/*
 * This source file was generated by the Gradle 'init' task
 */
package org.iorio;

import org.apache.commons.lang3.SystemUtils;
import org.iorio.core.configuration.SecretConfigurator;
import org.iorio.core.diff.CheckDifferenceImpl;

import java.io.IOException;

public class App {

    public static void main(String[] args) {
        SecretConfigurator.readSecrets(".env", ".");
        try {
            final var o = new CheckDifferenceImpl()
                    .checkDifference("MatteoIorio11",
                            "FinderTest",
                            System.getProperty("GITHUB_TOKEN"),
                            SystemUtils.getUserHome() + "/FinderTest",
                            "main",
                            "dev"
                    );
            System.out.println("Differences:");
            o.forEach(entry -> {
                System.out.println("Local: " + entry.x().getName() + " - " + entry.x().getPath());
                System.out.println("Remote: " + entry.y().getName() + " - " + entry.y().getPath());
            });
        }catch (Exception e) {
            e.printStackTrace();
        }
    }
}
