/*
 * This source file was generated by the Gradle 'init' task
 */
package org.iorio;

import org.apache.commons.lang3.SystemUtils;
import org.iorio.core.configuration.SecretConfigurator;
import org.iorio.core.diff.CheckDifference;

import java.io.IOException;

public class App {

    public static void main(String[] args) {
        SecretConfigurator.readSecrets(".env");
        try {
            final var o = CheckDifference
                    .checkDifference("MatteoIorio11",
                            "FinderTest",
                            System.getProperty("GITHUB_TOKEN"),
                            SystemUtils.getUserHome() + "/FinderTest",
                            "main",
                            "dev"
                    );
            System.out.println("Differences:");
            o.forEach(entry -> {
                System.out.println("Local: " + entry.getKey().getName() + " - " + entry.getKey().getPath());
                System.out.println("Remote: " + entry.getValue().getName() + " - " + entry.getValue().getPath());
            });
        }catch (IOException e) {
            e.printStackTrace();
        }
    }
}
